"""add publidhed on Post model

Revision ID: 250e5590dc34
Revises: 8b0d81939b1c
Create Date: 2023-12-25 16:14:18.199449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '250e5590dc34'
down_revision: Union[str, None] = '8b0d81939b1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('published', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'published')
    # ### end Alembic commands ###
