"""update post model

Revision ID: 4fd314bac941
Revises: c83f75f08d5e
Create Date: 2023-12-21 16:31:39.561667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fd314bac941'
down_revision: Union[str, None] = 'c83f75f08d5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('slug', sa.String(length=100), nullable=False))
    op.add_column('posts', sa.Column('anons', sa.String(length=500), nullable=False))
    op.add_column('posts', sa.Column('views', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'views')
    op.drop_column('posts', 'anons')
    op.drop_column('posts', 'slug')
    # ### end Alembic commands ###
